### ISSUE TITLE
Regeln aktualisieren

### ISSUE THREAD

**Issue by reworc** [GesellschaftFuerTechnischeVisualistik/gtv-linter-config#6]
* `@typescript-eslint/no-unused-vars-experimental` wurde in `'@typescript-eslint/no-unused-vars` umbenannt (`src/typescript.ts`)
* `jsdoc/newline-after-description` exisitiert nicht mehr (in `src/jsdoc.ts`)
* Damit verbleiben keine Regeln mehr für `jsdoc`, womit zu überlegen wäre, ob es komplett entfernt werden sollte

**Comment by tgeissler** [comment]
Kommt mitsamt dem neuen Patch
